// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: cheqd/did/v2/fee.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// FeeParams defines the parameters for the `did` module fixed fee.
type FeeParams struct {
	// Tx types define the fixed fee each for the `did` module.
	TxTypes    map[string]types.Coin                  `protobuf:"bytes,1,rep,name=tx_types,json=txTypes,proto3" json:"tx_types" yaml:"tx_types" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	BurnFactor github_com_cosmos_cosmos_sdk_types.Dec `protobuf:"bytes,2,opt,name=burn_factor,json=burnFactor,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Dec" json:"burn_factor"`
}

func (m *FeeParams) Reset()         { *m = FeeParams{} }
func (m *FeeParams) String() string { return proto.CompactTextString(m) }
func (*FeeParams) ProtoMessage()    {}
func (*FeeParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_b0cfbae270deaac7, []int{0}
}
func (m *FeeParams) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *FeeParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_FeeParams.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *FeeParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FeeParams.Merge(m, src)
}
func (m *FeeParams) XXX_Size() int {
	return m.Size()
}
func (m *FeeParams) XXX_DiscardUnknown() {
	xxx_messageInfo_FeeParams.DiscardUnknown(m)
}

var xxx_messageInfo_FeeParams proto.InternalMessageInfo

func (m *FeeParams) GetTxTypes() map[string]types.Coin {
	if m != nil {
		return m.TxTypes
	}
	return nil
}

func init() {
	proto.RegisterType((*FeeParams)(nil), "cheqd.did.v2.FeeParams")
	proto.RegisterMapType((map[string]types.Coin)(nil), "cheqd.did.v2.FeeParams.TxTypesEntry")
}

func init() { proto.RegisterFile("cheqd/did/v2/fee.proto", fileDescriptor_b0cfbae270deaac7) }

var fileDescriptor_b0cfbae270deaac7 = []byte{
	// 374 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x51, 0xcd, 0x6a, 0xea, 0x40,
	0x18, 0xcd, 0x28, 0xf7, 0xc7, 0x51, 0xb8, 0x97, 0x70, 0xb9, 0x57, 0x5d, 0x8c, 0x22, 0x97, 0x22,
	0x85, 0xcc, 0x60, 0xba, 0x29, 0xd2, 0x95, 0xb5, 0xd2, 0x65, 0x09, 0x16, 0x4a, 0xa1, 0xc8, 0x64,
	0x32, 0x6a, 0xd0, 0x64, 0x6c, 0x32, 0xa6, 0xe6, 0x2d, 0xba, 0xef, 0x0b, 0xf4, 0x01, 0xfa, 0x10,
	0x2e, 0xa5, 0xab, 0xd2, 0x85, 0x94, 0xf8, 0x06, 0x7d, 0x82, 0x92, 0x49, 0x5a, 0x5c, 0xcd, 0x37,
	0x73, 0xce, 0x77, 0xce, 0xe1, 0x0c, 0xfc, 0xcb, 0xa6, 0xfc, 0xd6, 0x21, 0x8e, 0xeb, 0x90, 0xc8,
	0x24, 0x63, 0xce, 0xf1, 0x22, 0x10, 0x52, 0xe8, 0x15, 0xf5, 0x8e, 0x1d, 0xd7, 0xc1, 0x91, 0x59,
	0xff, 0x33, 0x11, 0x13, 0xa1, 0x00, 0x92, 0x4e, 0x19, 0xa7, 0x8e, 0x98, 0x08, 0x3d, 0x11, 0x12,
	0x9b, 0x86, 0x9c, 0x44, 0x1d, 0x9b, 0x4b, 0xda, 0x21, 0x4c, 0xb8, 0x7e, 0x8e, 0xd7, 0x32, 0x7c,
	0x94, 0x2d, 0x66, 0x97, 0x0c, 0x6a, 0x3d, 0x14, 0x60, 0x69, 0xc0, 0xf9, 0x05, 0x0d, 0xa8, 0x17,
	0xea, 0x57, 0xf0, 0xa7, 0x5c, 0x8d, 0x64, 0xbc, 0xe0, 0x61, 0x15, 0x34, 0x8b, 0xed, 0xb2, 0xf9,
	0x1f, 0xef, 0xfb, 0xe3, 0x2f, 0x2a, 0x1e, 0xae, 0x86, 0x29, 0xed, 0xcc, 0x97, 0x41, 0xdc, 0xfb,
	0xb7, 0xde, 0x36, 0xb4, 0xf7, 0x6d, 0xe3, 0x57, 0x4c, 0xbd, 0x79, 0xb7, 0xf5, 0xa9, 0xd1, 0xb2,
	0x7e, 0xc8, 0x8c, 0xa6, 0xdf, 0xc0, 0xb2, 0xbd, 0x0c, 0xfc, 0xd1, 0x98, 0x32, 0x29, 0x82, 0x6a,
	0xa1, 0x09, 0xda, 0xa5, 0xde, 0x49, 0xba, 0xf6, 0xba, 0x6d, 0x1c, 0x4c, 0x5c, 0x39, 0x5d, 0xda,
	0x98, 0x09, 0x2f, 0x4f, 0x97, 0x1f, 0x46, 0xe8, 0xcc, 0x88, 0x92, 0xc2, 0x7d, 0xce, 0x9e, 0x9f,
	0x0c, 0x98, 0x87, 0xef, 0x73, 0x66, 0xc1, 0x54, 0x70, 0xa0, 0xf4, 0xea, 0x97, 0xb0, 0xb2, 0x1f,
	0x48, 0xff, 0x0d, 0x8b, 0x33, 0x1e, 0x57, 0x41, 0x6a, 0x63, 0xa5, 0xa3, 0x4e, 0xe0, 0xb7, 0x88,
	0xce, 0x97, 0x5c, 0x59, 0x97, 0xcd, 0x1a, 0xce, 0x95, 0xd2, 0xce, 0x70, 0xde, 0x19, 0x3e, 0x15,
	0xae, 0x6f, 0x65, 0xbc, 0x6e, 0xe1, 0x18, 0xf4, 0xce, 0x1f, 0x13, 0x04, 0xd6, 0x09, 0x02, 0x9b,
	0x04, 0x81, 0xb7, 0x04, 0x81, 0xfb, 0x1d, 0xd2, 0x36, 0x3b, 0xa4, 0xbd, 0xec, 0x90, 0x76, 0x7d,
	0xb8, 0x1f, 0x9b, 0xfa, 0xe2, 0xce, 0x60, 0x82, 0xa8, 0xba, 0x0c, 0x5f, 0x38, 0x9c, 0xac, 0xd4,
	0x6f, 0xaa, 0xf8, 0xf6, 0x77, 0x55, 0xf7, 0xd1, 0x47, 0x00, 0x00, 0x00, 0xff, 0xff, 0x78, 0x63,
	0x28, 0xe6, 0xe7, 0x01, 0x00, 0x00,
}

func (this *FeeParams) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*FeeParams)
	if !ok {
		that2, ok := that.(FeeParams)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if len(this.TxTypes) != len(that1.TxTypes) {
		return false
	}
	for i := range this.TxTypes {
		a := this.TxTypes[i]
		b := that1.TxTypes[i]
		if !(&a).Equal(&b) {
			return false
		}
	}
	if !this.BurnFactor.Equal(that1.BurnFactor) {
		return false
	}
	return true
}
func (m *FeeParams) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *FeeParams) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *FeeParams) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size := m.BurnFactor.Size()
		i -= size
		if _, err := m.BurnFactor.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintFee(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if len(m.TxTypes) > 0 {
		for k := range m.TxTypes {
			v := m.TxTypes[k]
			baseI := i
			{
				size, err := (&v).MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintFee(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
			i -= len(k)
			copy(dAtA[i:], k)
			i = encodeVarintFee(dAtA, i, uint64(len(k)))
			i--
			dAtA[i] = 0xa
			i = encodeVarintFee(dAtA, i, uint64(baseI-i))
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintFee(dAtA []byte, offset int, v uint64) int {
	offset -= sovFee(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *FeeParams) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.TxTypes) > 0 {
		for k, v := range m.TxTypes {
			_ = k
			_ = v
			l = v.Size()
			mapEntrySize := 1 + len(k) + sovFee(uint64(len(k))) + 1 + l + sovFee(uint64(l))
			n += mapEntrySize + 1 + sovFee(uint64(mapEntrySize))
		}
	}
	l = m.BurnFactor.Size()
	n += 1 + l + sovFee(uint64(l))
	return n
}

func sovFee(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozFee(x uint64) (n int) {
	return sovFee(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *FeeParams) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowFee
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: FeeParams: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: FeeParams: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TxTypes", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFee
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthFee
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthFee
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.TxTypes == nil {
				m.TxTypes = make(map[string]types.Coin)
			}
			var mapkey string
			mapvalue := &types.Coin{}
			for iNdEx < postIndex {
				entryPreIndex := iNdEx
				var wire uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowFee
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					wire |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				fieldNum := int32(wire >> 3)
				if fieldNum == 1 {
					var stringLenmapkey uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowFee
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						stringLenmapkey |= uint64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					intStringLenmapkey := int(stringLenmapkey)
					if intStringLenmapkey < 0 {
						return ErrInvalidLengthFee
					}
					postStringIndexmapkey := iNdEx + intStringLenmapkey
					if postStringIndexmapkey < 0 {
						return ErrInvalidLengthFee
					}
					if postStringIndexmapkey > l {
						return io.ErrUnexpectedEOF
					}
					mapkey = string(dAtA[iNdEx:postStringIndexmapkey])
					iNdEx = postStringIndexmapkey
				} else if fieldNum == 2 {
					var mapmsglen int
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowFee
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						mapmsglen |= int(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					if mapmsglen < 0 {
						return ErrInvalidLengthFee
					}
					postmsgIndex := iNdEx + mapmsglen
					if postmsgIndex < 0 {
						return ErrInvalidLengthFee
					}
					if postmsgIndex > l {
						return io.ErrUnexpectedEOF
					}
					mapvalue = &types.Coin{}
					if err := mapvalue.Unmarshal(dAtA[iNdEx:postmsgIndex]); err != nil {
						return err
					}
					iNdEx = postmsgIndex
				} else {
					iNdEx = entryPreIndex
					skippy, err := skipFee(dAtA[iNdEx:])
					if err != nil {
						return err
					}
					if (skippy < 0) || (iNdEx+skippy) < 0 {
						return ErrInvalidLengthFee
					}
					if (iNdEx + skippy) > postIndex {
						return io.ErrUnexpectedEOF
					}
					iNdEx += skippy
				}
			}
			m.TxTypes[mapkey] = *mapvalue
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BurnFactor", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFee
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthFee
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthFee
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.BurnFactor.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipFee(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthFee
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipFee(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowFee
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowFee
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowFee
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthFee
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupFee
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthFee
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthFee        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowFee          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupFee = fmt.Errorf("proto: unexpected end of group")
)
