name: "Workflow Dispatch"
on: push
concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true


jobs:

  call-release:
    name: "Release"
    uses: ./.github/workflows/release.yml
    secrets: inherit
